// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tbfdameweikimjekkmab.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRiZmRhbWV3ZWlraW1qZWtrbWFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNDMyMjgsImV4cCI6MjA3MDgxOTIyOH0.qYzw1_8ob4KxQeQYeodWl1UXFeZ_Z60CaNZ3rROjWs4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});